[world]
name = "Ronin Pact"
description = "A serverless quest system with dynamic NFT for the Cartridge Game Jam. Complete three trials and forge your pact."
seed = "ronin_quest"

[namespace]
default = "ronin_quest"

[env]
rpc_url = "http://localhost:5050/"
# Default Katana account (katana --dev --dev.accounts 3 --dev.seed 0)
account_address = "0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7"
private_key = "0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b"
# world_address = "0x..."  # Uncomment after first deployment

[writers]
"ronin_quest" = ["ronin_quest-actions"]
