[world]
name = "Ronin Quest"
description = "A serverless quest system with dynamic NFT for the Dojo ecosystem"
seed = "ronin_quest"

[namespace]
default = "ronin_quest"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7"
private_key = "0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b"
world_address = "0x005d7df3f6e6e44c78b7bd7716f942745aefd2f1aad006aaf8bd03c64ada96d0"

[writers]
"ronin_quest" = ["ronin_quest-actions"]

[[external_contracts]]
contract_name = "RoninPact"
instance_name = "ronin_pact"
salt = "1"
constructor_data = [
    "0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7"
]
