[world]
name = "Ronin Quest"
description = "A serverless quest system with dynamic NFT for the Dojo ecosystem"
seed = "ronin_quest"

[namespace]
default = "ronin_quest"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
# Authentication via Starkli keystore
# Set STARKNET_ACCOUNT environment variable to your keystore path:
#   export STARKNET_ACCOUNT=~/.starkli-wallets/deployer-mainnet-account.json
# world_address = "0x..."  # Uncomment after first deployment

[writers]
"ronin_quest" = ["ronin_quest-actions"]

[[external_contracts]]
contract_name = "RoninPact"
instance_name = "ronin_pact"
salt = "1"
constructor_data = [
    "$DOJO_ACCOUNT_ADDRESS"
]
