[world]
name = "Ronin Pact"
description = "A serverless quest system with dynamic NFT for the Cartridge Game Jam. Complete three trials and forge your pact."
seed = "ronin_quest"

[namespace]
default = "ronin_quest"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
# Credentials loaded from .env file
# Set DOJO_ACCOUNT_ADDRESS and DOJO_PRIVATE_KEY in .env
account_address = "$DOJO_ACCOUNT_ADDRESS"
private_key = "$DOJO_PRIVATE_KEY"
# world_address = "0x..."  # Uncomment after first deployment

[writers]
"ronin_quest" = ["ronin_quest-actions"]
